name: Example Workflow Using Default Env Variables

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print GitHub Environment Variables
        run: |
          echo "Print Environment variable: $GITHUB_REPOSITORY_ID"
          echo "Print Environment variable: $GITHUB_OUTPUT"
          
          
          
          
